services:
  - type: web
    name: deploiement-test
    plan: free
    env: docker # option recommandée si Java doit être correctement géré
    dockerfilePath: Dockerfile
    # buildCommand: |
    #   echo "JAVA_HOME=$JAVA_HOME"
    #   java -version
    #   javac -version
    #   ./mvnw clean install
    # startCommand: java -jar target/deploiement_test-0.0.1-SNAPSHOT.jar
    envVars:
      # - key: PORT
      #   value: "8080"
      - key: JAVA_VERSION
        value: 11
      - key: DB_URL
        fromGroup: groupforthefirsttest
      - key: DB_USERNAME
        fromGroup: groupforthefirsttest
      - key: DB_PASSWORD
        fromGroup: groupforthefirsttest
      
