services:
  - type: web
    name: deploiement-test
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/deploiement_test-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: DB_URL
        fromGroup: groupforthefirsttest
      - key: DB_USERNAME
        fromGroup: groupforthefirsttest
      - key: DB_PASSWORD
        fromGroup: groupforthefirsttest

