spring.application.name=deploiement_test
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# Empêche Spring Boot de planter si la base est inaccessible
# spring.spl.init.mode=never
spring.datasource.initialization-mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

server.port=8080
server.address=0.0.0.0

